### ISSUE TITLE
Cant start app

### ISSUE THREAD

**Issue by aporzio1** [samcm/PlexTogether#17]
I was able to get the server running but receive the same error on 2 different Macs

Running macOS 10.11.6

```
0 info it worked if it ends with okay
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle plexTogether@0.1.0~prestart: plexTogether@0.1.0
6 silly lifecycle plexTogether@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle plexTogether@0.1.0~start: plexTogether@0.1.0
8 verbose lifecycle plexTogether@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle plexTogether@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/PlexTogether/app/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin
10 verbose lifecycle plexTogether@0.1.0~start: CWD: /PlexTogether/app
11 silly lifecycle plexTogether@0.1.0~start: Args: [ '-c', 'electron app/app' ]
12 info lifecycle plexTogether@0.1.0~start: Failed to exec start script
13 verbose stack Error: plexTogether@0.1.0 start: `electron app/app`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid plexTogether@0.1.0
15 verbose cwd /PlexTogether/app
16 error Darwin 15.6.0
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 error node v6.9.4
19 error nam  v3.10.10
20 error file sh
21 error code LIFECYCLE
22 error errno ENOENT
23 error sys call spawn
24 error plexTogether@0.1.0 start: `electron app/app`
24 error spawn ENOENT
25 error Failed at the plexTogether@0.1.0 start script 'electron app/app'.
25 error Make sure you have the latest version of node.js and nam installed.
25 error If you do, this is most likely a problem with the plexTogether package,
25 error not with nam itself.
25 error Tell the author that this fails on your system:
25 error     electron app/app
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs plexTogether
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls plexTogether
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by samcm** [comment]
Does 'npm install' throw any errors? And do you have any anti virus installed? Seems like some of them don't like Electron when it gets installed.

**Comment by aporzio1** [comment]
When I run `npm install` only output is this

`npm WARN plexTogether@0.1.0 No repository field.`

and no antivirus is installed

**Comment by aporzio1** [comment]
Update: After running `npm install -g electron` I am able to open the app. But only by running the command `electron` and dragging the app folder to the electron window.

if i run `npm start` i get 

> Unable to find Electron app at /PlexTogether/app/app/app
> 
> Cannot find module '/PlexTogether/app/app/app'

**Comment by Hink1** [comment]
I still can't get the client app to run/install after installing the electron package with npm.

**Comment by samcm** [comment]
As the Electron app is now discontinued I'm going to close this
